export const $ = (selector) => document.querySelector(selector);
export const $$ = (selector) => Array.from(document.querySelectorAll(selector));

export const elements = {
  pageTitle: $("#pageTitle"),
  roleSelect: $("#roleSelect"),
  roleBadge: $("#roleBadge"),
  programFilter: $("#programFilter"),
  provinceFilter: $("#provinceFilter"),
  periodFilter: $("#periodFilter"),
  metricGrid: $("#metricGrid"),
  programChart: $("#programChart"),
  riskList: $("#riskList"),
  recentReports: $("#recentReports"),
  reportForm: $("#reportForm"),
  reportProgram: $("#reportProgram"),
  reportProvince: $("#reportProvince"),
  reportIndicator: $("#reportIndicator"),
  reportPeriod: $("#reportPeriod"),
  indicatorBoard: $("#indicatorBoard"),
  designProgramSelect: $("#designProgramSelect"),
  expectedResults: $("#expectedResults"),
  indicatorSuggestions: $("#indicatorSuggestions"),
  formsProgramSelect: $("#formsProgramSelect"),
  formTemplateGrid: $("#formTemplateGrid"),
  formUploadInput: $("#formUploadInput"),
  uploadFormButton: $("#uploadFormButton"),
  uploadStatus: $("#uploadStatus"),
  uploadPreview: $("#uploadPreview"),
  chartMetricGrid: $("#chartMetricGrid"),
  indicatorChartTypeSelect: $("#indicatorChartTypeSelect"),
  periodChartTypeSelect: $("#periodChartTypeSelect"),
  indicatorCharts: $("#indicatorCharts"),
  periodCharts: $("#periodCharts"),
  submissionList: $("#submissionList"),
  conceptCount: $("#conceptCount"),
  conceptPaperList: $("#conceptPaperList"),
  conceptDetailTitle: $("#conceptDetailTitle"),
  conceptPaperDetail: $("#conceptPaperDetail"),
  reviewList: $("#reviewList"),
  actionList: $("#actionList"),
  programGrid: $("#programGrid"),
  toast: $("#toast"),
};
